In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

[]

In [2]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "openaq" dataset
dataset_ref = client.dataset("openaq", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

# List all the tables in the "openaq" dataset
tables = list(client.list_tables(dataset))

# Print names of all tables in the dataset (there's only one!)
for table in tables:  
    print(table.table_id)

Using Kaggle's public dataset BigQuery integration.
global_air_quality

In [3]:
# Construct a reference to the "global_air_quality" table
table_ref = dataset_ref.table("global_air_quality")

# API request - fetch the table
table = client.get_table(table_ref)

# Preview the first five lines of the "global_air_quality" table
client.list_rows(table, max_results=5).to_dataframe()

                        location          ...           averaged_over_in_hours
0  BTM Layout, Bengaluru - KSPCB          ...                             0.25
1  BTM Layout, Bengaluru - KSPCB          ...                             0.25
2  BTM Layout, Bengaluru - KSPCB          ...                             0.25
3  BTM Layout, Bengaluru - KSPCB          ...                             0.25
4  BTM Layout, Bengaluru - KSPCB          ...                             0.25

[5 rows x 11 columns]

In [4]:
table.schema

[SchemaField('location', 'STRING', 'NULLABLE', 'Location where data was measured', ()),
 SchemaField('city', 'STRING', 'NULLABLE', 'City containing location', ()),
 SchemaField('country', 'STRING', 'NULLABLE', 'Country containing measurement in 2 letter ISO code', ()),
 SchemaField('pollutant', 'STRING', 'NULLABLE', 'Name of the Pollutant being measured. Allowed values: PM25, PM10, SO2, NO2, O3, CO, BC', ()),
 SchemaField('value', 'FLOAT', 'NULLABLE', 'Latest measured value for the pollutant', ()),
 SchemaField('timestamp', 'TIMESTAMP', 'NULLABLE', 'The datetime at which the pollutant was measured, in ISO 8601 format', ()),
 SchemaField('unit', 'STRING', 'NULLABLE', 'The unit the value was measured in coded by UCUM Code', ()),
 SchemaField('source_name', 'STRING', 'NULLABLE', 'Name of the source of the data', ()),
 SchemaField('latitude', 'FLOAT', 'NULLABLE', 'Latitude in decimal degrees. Precision >3 decimal points.', ()),
 SchemaField('longitude', 'FLOAT', 'NULLABLE', 'Longitude in decimal degrees. Precision >3 decimal points.', ()),
 SchemaField('averaged_over_in_hours', 'FLOAT', 'NULLABLE', 'The number of hours the value was averaged over.', ())]

In [5]:
# Query to select all the items from the "city" column where the "country" column is 'US'
query = """
        SELECT city
        FROM `bigquery-public-data.openaq.global_air_quality`
        WHERE country = 'US'
        """

In [6]:
query_job = client.query(query)

In [7]:
# API request - run the query, and return a pandas DataFrame
us_cities = query_job.to_dataframe()

In [8]:
us_cities

                      city
0                  Houston
1                  Houston
2                  Houston
3                  Houston
4                  Houston
5                  Houston
6                  Houston
7                  Houston
8                  Houston
9                  Houston
10                 Houston
11                 Houston
12                 Houston
13                 Houston
14                 Houston
15                 Houston
16                 Houston
17                 Houston
18                 Houston
19                 Houston
20                 Houston
21                 Houston
22                 Houston
23                 Houston
24                 Houston
25                 Houston
26                 Houston
27                 Houston
28                 Houston
29                 Houston
...                    ...
3537                   MT1
3538                   MT1
3539              BOUNDARY
3540               WHATCOM
3541            Bellingham
3542              BOUNDARY
3543               WHATCOM
3544            Bellingham
3545            Bellingham
3546  FS1 - Forest Service
3547              BOUNDARY
3548                JUNEAU
3549             Anchorage
3550             Anchorage
3551             Anchorage
3552             Anchorage
3553     MATANUSKA-SUSITNA
3554     MATANUSKA-SUSITNA
3555     MATANUSKA-SUSITNA
3556     MATANUSKA-SUSITNA
3557         YUKON-KOYUKUK
3558             Fairbanks
3559             Fairbanks
3560             Fairbanks
3561             Fairbanks
3562             Fairbanks
3563             Fairbanks
3564               Atlanta
3565       Mammoth Cave NP
3566                Moscow

[3567 rows x 1 columns]

In [9]:
us_cities.city.value_counts().head()

Phoenix-Mesa-Scottsdale                     87
Houston                                     82
Los Angeles-Long Beach-Santa Ana            63
New York-Northern New Jersey-Long Island    60
Riverside-San Bernardino-Ontario            59
Name: city, dtype: int64

In [10]:
query = """
        SELECT city
            ,source_name
        FROM `bigquery-public-data.openaq.global_air_quality`
        WHERE country = 'US'
        """

In [11]:
query_job = client.query(query)

In [12]:
us_city_country = query_job.to_dataframe()

In [13]:
us_city_country

                      city source_name
0                  Houston       Texas
1                  Houston       Texas
2                  Houston       Texas
3                  Houston       Texas
4                  Houston       Texas
5                  Houston       Texas
6                  Houston       Texas
7                  Houston       Texas
8                  Houston       Texas
9                  Houston       Texas
10                 Houston       Texas
11                 Houston       Texas
12                 Houston       Texas
13                 Houston       Texas
14                 Houston       Texas
15                 Houston       Texas
16                 Houston       Texas
17                 Houston       Texas
18                 Houston       Texas
19                 Houston       Texas
20                 Houston       Texas
21                 Houston       Texas
22                 Houston       Texas
23                 Houston       Texas
24                 Houston       Texas
25                 Houston       Texas
26                 Houston       Texas
27                 Houston       Texas
28                 Houston       Texas
29                 Houston       Texas
...                    ...         ...
3537                   MT1      AirNow
3538                   MT1      AirNow
3539              BOUNDARY      AirNow
3540               WHATCOM      AirNow
3541            Bellingham      AirNow
3542              BOUNDARY      AirNow
3543               WHATCOM      AirNow
3544            Bellingham      AirNow
3545            Bellingham      AirNow
3546  FS1 - Forest Service      AirNow
3547              BOUNDARY      AirNow
3548                JUNEAU      AirNow
3549             Anchorage      AirNow
3550             Anchorage      AirNow
3551             Anchorage      AirNow
3552             Anchorage      AirNow
3553     MATANUSKA-SUSITNA      AirNow
3554     MATANUSKA-SUSITNA      AirNow
3555     MATANUSKA-SUSITNA      AirNow
3556     MATANUSKA-SUSITNA      AirNow
3557         YUKON-KOYUKUK      AirNow
3558             Fairbanks      AirNow
3559             Fairbanks      AirNow
3560             Fairbanks      AirNow
3561             Fairbanks      AirNow
3562             Fairbanks      AirNow
3563             Fairbanks      AirNow
3564               Atlanta     Spartan
3565       Mammoth Cave NP     Spartan
3566                Moscow      AirNow

[3567 rows x 2 columns]

In [14]:
query = """
        SELECT *
        FROM `bigquery-public-data.openaq.global_air_quality`
        WHERE country = 'US'
        """

In [15]:
query_job = client.query(query)

In [16]:
select_all = query_job.to_dataframe()

In [17]:
select_all

                                   location          ...           averaged_over_in_hours
0             Freeport South Avenue I C1012          ...                              1.0
1                        Lake Jackson C1016          ...                              1.0
2                             Danciger C618          ...                              1.0
3                             Danciger C618          ...                              1.0
4        Galveston 99th St. C1034/A320/X183          ...                              1.0
5        Galveston 99th St. C1034/A320/X183          ...                              1.0
6                        Mustang Bayou C619          ...                              1.0
7                        Mustang Bayou C619          ...                              1.0
8           Texas City Ball Park A147/C1022          ...                              1.0
9                    UH Coastal Center C697          ...                              1.0
10                   UH Coastal Center C697          ...                              1.0
11                 Texas City 34th St. C620          ...                              1.0
12                 Texas City 34th St. C620          ...                              1.0
13                    Manvel Croix Park C84          ...                              1.0
14                    Manvel Croix Park C84          ...                              1.0
15                                   U of H          ...                              1.0
16             Seabrook Friendship Park C45          ...                              1.0
17             Seabrook Friendship Park C45          ...                              1.0
18             Seabrook Friendship Park C45          ...                              1.0
19                            Tom Bass C558          ...                              1.0
20                     Houston Croquet C409          ...                              1.0
21                      Houston Monroe C406          ...                              1.0
22               La Porte Sylvan Beach C556          ...                              1.0
23    Hou.DeerPrk2 C35/235/1001/AFH139FP239          ...                              1.0
24    Hou.DeerPrk2 C35/235/1001/AFH139FP239          ...                              1.0
25    Hou.DeerPrk2 C35/235/1001/AFH139FP239          ...                              1.0
26    Hou.DeerPrk2 C35/235/1001/AFH139FP239          ...                              1.0
27                          Park Place C416          ...                              1.0
28                          Park Place C416          ...                              1.0
29            Houston Bayland Park C53/A146          ...                              1.0
...                                     ...          ...                              ...
3537                                  Havre          ...                              1.0
3538                               Cut Bank          ...                              1.0
3539                        Boundary County          ...                              1.0
3540                      Bellingham Pacifc          ...                              1.0
3541                      Bellingham-Yew St          ...                              1.0
3542                                Mt Hall          ...                              1.0
3543                   Maple Falls-Azure Wa          ...                              1.0
3544                   Custer-Loomis (SO-AQ          ...                              1.0
3545                   Custer-Loomis (SO-AQ          ...                              1.0
3546                                Unit153          ...                              1.0
3547                               Porthill          ...                              1.0
3548                           Floyd Dryden          ...                              1.0
3549                                 Garden          ...                              1.0
3550                                 Garden          ...                              1.0
3551                   Parkgate (Eagle Rive          ...                              1.0
3552                   Parkgate (Eagle Rive          ...                              1.0
3553                   Butte (Harrison Cour          ...                              1.0
3554                   Butte (Harrison Cour          ...                              1.0
3555                                 Palmer          ...                              1.0
3556                                 Palmer          ...                              1.0
3557                             Denali NPP          ...                              1.0
3558                             Hurst Road          ...                              1.0
3559                                  NCore          ...                              1.0
3560                                  NCore          ...                              1.0
3561                                  NCore          ...                              1.0
3562                                  NCore          ...                              1.0
3563                                  NCore          ...                              1.0
3564             SPARTAN - Emory University          ...                              1.0
3565                 SPARTAN - Mammoth Cave          ...                              1.0
3566                                 Moscow          ...                              1.0

[3567 rows x 11 columns]

In [18]:
query = """
        SELECT *
        FROM `bigquery-public-data.openaq.global_air_quality`
        WHERE country = "US"
        """

# Create a Query JobConfig object to estimate size of query without running i
dry_run_config = bigquery.QueryJobConfig(dry_run=True)

# API request - dry run query to estimate costs
dry_run_query_job = client.query(query, job_config=dry_run_config)

print("This query will process {} bytes,".format(dry_run_query_job.total_bytes_processed))

This query will process 2394379 bytes,

In [19]:
# Only run the query if it's less than 100 MB
ONE_HUNDRED_MB = 100*1000*1000
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=ONE_HUNDRED_MB)

#Set up the query (will only run if it's less than 100 MB)
safe_query_job = client.query(query, job_config=safe_config)

#API request - try to run the query, and return a pandas DataFrame
safe_query_job.to_dataframe()

                                   location          ...           averaged_over_in_hours
0             Freeport South Avenue I C1012          ...                              1.0
1                        Lake Jackson C1016          ...                              1.0
2                             Danciger C618          ...                              1.0
3                             Danciger C618          ...                              1.0
4        Galveston 99th St. C1034/A320/X183          ...                              1.0
5        Galveston 99th St. C1034/A320/X183          ...                              1.0
6                        Mustang Bayou C619          ...                              1.0
7                        Mustang Bayou C619          ...                              1.0
8           Texas City Ball Park A147/C1022          ...                              1.0
9                    UH Coastal Center C697          ...                              1.0
10                   UH Coastal Center C697          ...                              1.0
11                 Texas City 34th St. C620          ...                              1.0
12                 Texas City 34th St. C620          ...                              1.0
13                    Manvel Croix Park C84          ...                              1.0
14                    Manvel Croix Park C84          ...                              1.0
15                                   U of H          ...                              1.0
16             Seabrook Friendship Park C45          ...                              1.0
17             Seabrook Friendship Park C45          ...                              1.0
18             Seabrook Friendship Park C45          ...                              1.0
19                            Tom Bass C558          ...                              1.0
20                     Houston Croquet C409          ...                              1.0
21                      Houston Monroe C406          ...                              1.0
22               La Porte Sylvan Beach C556          ...                              1.0
23    Hou.DeerPrk2 C35/235/1001/AFH139FP239          ...                              1.0
24    Hou.DeerPrk2 C35/235/1001/AFH139FP239          ...                              1.0
25    Hou.DeerPrk2 C35/235/1001/AFH139FP239          ...                              1.0
26    Hou.DeerPrk2 C35/235/1001/AFH139FP239          ...                              1.0
27                          Park Place C416          ...                              1.0
28                          Park Place C416          ...                              1.0
29            Houston Bayland Park C53/A146          ...                              1.0
...                                     ...          ...                              ...
3537                                  Havre          ...                              1.0
3538                               Cut Bank          ...                              1.0
3539                        Boundary County          ...                              1.0
3540                      Bellingham Pacifc          ...                              1.0
3541                      Bellingham-Yew St          ...                              1.0
3542                                Mt Hall          ...                              1.0
3543                   Maple Falls-Azure Wa          ...                              1.0
3544                   Custer-Loomis (SO-AQ          ...                              1.0
3545                   Custer-Loomis (SO-AQ          ...                              1.0
3546                                Unit153          ...                              1.0
3547                               Porthill          ...                              1.0
3548                           Floyd Dryden          ...                              1.0
3549                                 Garden          ...                              1.0
3550                                 Garden          ...                              1.0
3551                   Parkgate (Eagle Rive          ...                              1.0
3552                   Parkgate (Eagle Rive          ...                              1.0
3553                   Butte (Harrison Cour          ...                              1.0
3554                   Butte (Harrison Cour          ...                              1.0
3555                                 Palmer          ...                              1.0
3556                                 Palmer          ...                              1.0
3557                             Denali NPP          ...                              1.0
3558                             Hurst Road          ...                              1.0
3559                                  NCore          ...                              1.0
3560                                  NCore          ...                              1.0
3561                                  NCore          ...                              1.0
3562                                  NCore          ...                              1.0
3563                                  NCore          ...                              1.0
3564             SPARTAN - Emory University          ...                              1.0
3565                 SPARTAN - Mammoth Cave          ...                              1.0
3566                                 Moscow          ...                              1.0

[3567 rows x 11 columns]

In [20]:
# Only run the query if it's less than 1 GB
max_size_bytes = 10*1000*1000
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=max_size_bytes)

# Set up the query (will only run if it's less than 1 GB)
safe_query_job = client.query(query, job_config=safe_config)

# API request - try to run the query, and return a pandas DataFrame
job_post_scores = safe_query_job.to_dataframe()

# Print average score for job posts
job_post_scores.score.mean()

AttributeError: 'DataFrame' object has no attribute 'score'